export const SET_NAME_SOURCE = "SET_NAME_SOURCE";
export const SET_NAME_CATEGORY = "SET_NAME_CATEGORY";
export const SET_NAME_SUBCATEGORY = "SET_NAME_SUBCATEGORY";
export const TOGGLE_NAME_FILTER = "TOGGLE_NAME_FILTER";
export const SET_RESULT_COUNT = "SET_RESULT_COUNT";
export const GENERATE_NEW_RESULTS = "GENERATE_NEW_RESULTS";